---
title: "Mock Paper"
subtitle: "A reproducible manuscript written in Quarto."
format: html
---

## Introduction

What did the fox say. What did the fox say. What did the fox say. What
did the fox say. What did the fox say. What did the fox say. What did
the fox say. What did the fox say. What did the fox say @Fox2020.

## Data


For this paper we will be using some dummy data. The libraries and data
simulation or imports are shown above.

## Methods


We fit the following model. We specificied age as What did the fox say.

$$
y = x_1\beta_1 + x_2\beta_2 + x_2^2\beta_3 + \varepsilon
$$ {#eq-model}



## Foxes are not green

What did the fox say. What did the fox say. What did the fox say. What
did the fox say. What did the fox say. What did the fox say. What did
the fox say. What did the fox say. What did the fox say.


## Foxes like maps

What did the fox say. What did the fox say. What did the fox say. What
did the fox say. What did the fox say. What did the fox say. What did
the fox say. What did the fox say. What did the fox say.

## Model

What did the fox say. What did the fox say. What did the fox say. What
did the fox say. What did the fox say. What did the fox say. What did
the fox say. What did the fox say. What did the fox say.


## Discussion

Foxes are cute @Sparkes2022 We also show this in @fig-plot. However our
modeling reports that tail length significantly affects cuteness. What
did the fox say. What did the fox say. What did the fox say. What did
the fox say. What did the fox say. What did the fox say. What did the
fox say. What did the fox say. What did the fox say.
